services: # каждый сервис один контейнер
  db:
    image: postgres:16 # образ с докер хаб
    container_name: invest_db
    restart: always
    environment: # задаем переменные окружения внутри контейнера
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data # нужно чтобы наши данные сохранялись между перезапусками контейнера, иначе они просто потеряются
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:                    
    image: redis:7-alpine
    container_name: invest_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend # путь к директории сборки, где лежит наш докер файл
    container_name: invest_backend
    restart: always
    env_file:
      - .env
    depends_on: # зависимости между нашими сервисами
      db: # гарантируем, что сервис дб стартует раньше чем бэк, но не ждет полной готовности базы
        condition: service_healthy # setvice-healthy ожидает положительного статуса проверки healtcheck в сервисе db
      redis:
        condition: service_started
    expose:
      - "8000"
    ports:                          
      - "8000:8000"  

  nginx:
    image: nginx:1.27-alpine
    container_name: invest_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80" # порт на хосте (моя машина) : порт в контейнере
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certbot/www:/var/www/certbot:rw
      - ./nginx/certbot/conf:/etc/letsencrypt:rw

  certbot:
    image: certbot/certbot:latest
    container_name: invest_certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot:rw
      - ./nginx/certbot/conf:/etc/letsencrypt:rw

volumes:
  postgres_data:
  redis_data: